version: '3.9'

services:
  warehouse-service:
    build: .
    container_name: warehouse-service
    ports:
    # needs a top level .env for the PORT to take effect here
      - "${PORT:-8001}:8000"
    env_file:
      - ./warehouse_managment/.env
    volumes:
      - .:/app
    working_dir: /app/warehouse_managment
    restart: unless-stopped
    networks:
      - scms

networks:
  scms:
    name: scms-network
    external : true
